export type Destination = {
  city: string;
  country: string;
  code: string;
  arrivalId?: string;
  group: "Türkiye" | "Balkanlar" | "Kafkasya" | "Fas ve Kuzey Afrika" | "Türk dünyası" | "Müslüman Asya" | "Güney ve Güneydoğu Asya" | "Uzak rotalar" | "Rusya";
  minNights: number;
  maxNights: number;
  weekendOnly: boolean;
  visaSafe: boolean;
  weatherNote: string;
  tripPlan: string;
  transportMode?: "ground";
  transportLinks?: Array<{ label: string; url: string }>;
  entryNote?: string;
  entrySourceUrl?: string;
  riskNote?: string;
  manualOnly?: boolean;
  checkedAt?: string;
};

export const DESTINATIONS: Record<string, Destination> = {
  TBS: { code: "TBS", city: "Tiflis", country: "Gürcistan", group: "Kafkasya", minNights: 2, maxNights: 3, weekendOnly: true, visaSafe: true, weatherNote: "Serin dönem · 0°C altı günler elenir", tripPlan: "2–3 gece şehir" },
  GYD: { code: "GYD", city: "Bakü", country: "Azerbaycan", group: "Türk dünyası", minNights: 2, maxNights: 3, weekendOnly: true, visaSafe: true, weatherNote: "Kuvvetli rüzgâr günleri elenir", tripPlan: "2–3 gece şehir" },
  VAS: { code: "VAS", city: "Sivas", country: "Türkiye", group: "Türkiye", minNights: 2, maxNights: 3, weekendOnly: true, visaSafe: true, weatherNote: "0°C altı günler elenir", tripPlan: "2–3 gece şehir" },
  CMN: { code: "CMN", city: "Kazablanka", country: "Fas", group: "Fas ve Kuzey Afrika", minNights: 6, maxNights: 9, weekendOnly: false, visaSafe: true, weatherNote: "Ilıman dönem", tripPlan: "6–9 gün Fas rotası" },
  RAK: { code: "RAK", city: "Marakeş", country: "Fas", group: "Fas ve Kuzey Afrika", minNights: 6, maxNights: 9, weekendOnly: false, visaSafe: true, weatherNote: "35°C üzeri günler elenir", tripPlan: "6–9 gün Fas rotası" },
  FEZ: { code: "FEZ", city: "Fes", country: "Fas", group: "Fas ve Kuzey Afrika", minNights: 5, maxNights: 8, weekendOnly: false, visaSafe: true, weatherNote: "Aşırı sıcak günler elenir", tripPlan: "5–8 gün kültür rotası" },
  RBA: { code: "RBA", city: "Rabat", country: "Fas", group: "Fas ve Kuzey Afrika", minNights: 5, maxNights: 8, weekendOnly: false, visaSafe: true, weatherNote: "Ilıman dönem", tripPlan: "5–8 gün şehir ve okyanus" },
  AGA: { code: "AGA", city: "Agadir", country: "Fas", group: "Fas ve Kuzey Afrika", minNights: 6, maxNights: 9, weekendOnly: false, visaSafe: true, weatherNote: "Deniz sıcaklığı ayrıca doğrulanır", tripPlan: "6–9 gün sahil" },
  TAS: { code: "TAS", city: "Taşkent", country: "Özbekistan", group: "Türk dünyası", minNights: 5, maxNights: 8, weekendOnly: false, visaSafe: true, weatherNote: "Aşırı sıcak günler elenir", tripPlan: "5–8 gün Özbekistan" },
  SKD: { code: "SKD", city: "Semerkant", country: "Özbekistan", group: "Türk dünyası", minNights: 5, maxNights: 8, weekendOnly: false, visaSafe: true, weatherNote: "Aşırı sıcak günler elenir", tripPlan: "5–8 gün Semerkant–Buhara" },
  ALA: { code: "ALA", city: "Almatı", country: "Kazakistan", group: "Türk dünyası", minNights: 5, maxNights: 8, weekendOnly: false, visaSafe: true, weatherNote: "0°C altı günler elenir", tripPlan: "5–8 gün şehir ve doğa" },
  NQZ: { code: "NQZ", city: "Astana", country: "Kazakistan", group: "Türk dünyası", minNights: 4, maxNights: 7, weekendOnly: false, visaSafe: true, weatherNote: "Sert soğuk ve rüzgâr elenir", tripPlan: "4–7 gün şehir" },
  FRU: { code: "FRU", city: "Bişkek", country: "Kırgızistan", group: "Türk dünyası", minNights: 5, maxNights: 8, weekendOnly: false, visaSafe: true, weatherNote: "0°C altı günler elenir", tripPlan: "5–8 gün Bişkek–Issık Göl" },
  RMO: { code: "RMO", city: "Kişinev", country: "Moldova", group: "Türk dünyası", minNights: 3, maxNights: 5, weekendOnly: false, visaSafe: true, weatherNote: "0°C altı günler elenir", tripPlan: "3–5 gün Kişinev–Gagavuzya" },
  ECN: { code: "ECN", city: "Lefkoşa", country: "KKTC", group: "Türk dünyası", minNights: 3, maxNights: 5, weekendOnly: false, visaSafe: true, weatherNote: "Deniz sıcaklığı ayrıca doğrulanır", tripPlan: "3–5 gün şehir ve sahil" },
  SJJ: { code: "SJJ", city: "Saraybosna", country: "Bosna-Hersek", group: "Balkanlar", minNights: 2, maxNights: 3, weekendOnly: true, visaSafe: true, weatherNote: "0°C altı günler elenir", tripPlan: "2–3 gece şehir · Mostar ile 4–5 gün" },
  SKP: { code: "SKP", city: "Üsküp", country: "Kuzey Makedonya", group: "Balkanlar", minNights: 2, maxNights: 3, weekendOnly: true, visaSafe: true, weatherNote: "0°C altı günler elenir", tripPlan: "2–3 gece şehir · Ohri ile 4–5 gün" },
  OHD: { code: "OHD", city: "Ohri", country: "Kuzey Makedonya", group: "Balkanlar", minNights: 3, maxNights: 5, weekendOnly: false, visaSafe: true, weatherNote: "0°C altı günler elenir", tripPlan: "3–5 gün göl rotası" },
  TIA: { code: "TIA", city: "Tiran", country: "Arnavutluk", group: "Balkanlar", minNights: 2, maxNights: 3, weekendOnly: true, visaSafe: true, weatherNote: "35°C üzeri günler elenir", tripPlan: "2–3 gece şehir · Berat/sahil ile 4–8 gün" },
  PRN: { code: "PRN", city: "Priştine", country: "Kosova", group: "Balkanlar", minNights: 2, maxNights: 3, weekendOnly: true, visaSafe: true, weatherNote: "0°C altı günler elenir", tripPlan: "2–3 gece şehir · Prizren ile 3–4 gün" },
  TGD: { code: "TGD", city: "Podgoritsa", country: "Karadağ", group: "Balkanlar", minNights: 3, maxNights: 5, weekendOnly: false, visaSafe: true, weatherNote: "Sahil sezonu ayrıca değerlendirilir", tripPlan: "3–5 gün Kotor–Budva" },
  BEG: { code: "BEG", city: "Belgrad", country: "Sırbistan", group: "Balkanlar", minNights: 2, maxNights: 3, weekendOnly: true, visaSafe: true, weatherNote: "0°C altı günler elenir", tripPlan: "2–3 gece gece hayatı" },
  TUN: { code: "TUN", city: "Tunis", country: "Tunus", group: "Fas ve Kuzey Afrika", minNights: 5, maxNights: 8, weekendOnly: false, visaSafe: true, weatherNote: "35°C üzeri günler elenir", tripPlan: "5–8 gün Tunis–Sidi Bou Said–Sousse" },
  AMM: { code: "AMM", city: "Amman", country: "Ürdün", group: "Müslüman Asya", minNights: 6, maxNights: 8, weekendOnly: false, visaSafe: true, weatherNote: "Güvenlik ve aşırı sıcak ayrıca kontrol edilir", tripPlan: "6–8 gün Petra–Wadi Rum–Akabe" },
  DOH: { code: "DOH", city: "Doha", country: "Katar", group: "Müslüman Asya", minNights: 2, maxNights: 4, weekendOnly: false, visaSafe: true, weatherNote: "35°C üzeri günler elenir", tripPlan: "2–4 günlük kısa rota" },
  MCT: { code: "MCT", city: "Maskat", country: "Umman", group: "Müslüman Asya", minNights: 5, maxNights: 7, weekendOnly: false, visaSafe: false, weatherNote: "35°C üzeri günler elenir", tripPlan: "5–7 gün Maskat–Nizwa" },
  KUL: { code: "KUL", city: "Kuala Lumpur", country: "Malezya", group: "Müslüman Asya", minNights: 8, maxNights: 12, weekendOnly: false, visaSafe: true, weatherNote: "Çok yüksek nem ve muson elenir", tripPlan: "8–12 gün KL–Penang–Langkawi" },
  LGK: { code: "LGK", city: "Langkawi", country: "Malezya", group: "Müslüman Asya", minNights: 8, maxNights: 12, weekendOnly: false, visaSafe: true, weatherNote: "Deniz, nem ve muson birlikte kontrol edilir", tripPlan: "8–12 gün ada ve şehir" },
  CGK: { code: "CGK", city: "Cakarta", country: "Endonezya", group: "Müslüman Asya", minNights: 9, maxNights: 14, weekendOnly: false, visaSafe: false, weatherNote: "Çok yüksek nem ve muson elenir", tripPlan: "9–14 gün Endonezya" },
  YIA: { code: "YIA", city: "Yogyakarta", country: "Endonezya", group: "Müslüman Asya", minNights: 9, maxNights: 14, weekendOnly: false, visaSafe: false, weatherNote: "Çok yüksek nem ve muson elenir", tripPlan: "9–14 gün kültür rotası" },
  LOP: { code: "LOP", city: "Lombok", country: "Endonezya", group: "Müslüman Asya", minNights: 9, maxNights: 14, weekendOnly: false, visaSafe: false, weatherNote: "Deniz, nem ve muson birlikte kontrol edilir", tripPlan: "9–14 gün deniz ve doğa" },
  DPS: { code: "DPS", city: "Bali", country: "Endonezya", group: "Güney ve Güneydoğu Asya", minNights: 9, maxNights: 14, weekendOnly: false, visaSafe: false, weatherNote: "Deniz, nem ve muson birlikte kontrol edilir", tripPlan: "9–14 gün Bali–Lombok" },
  BKK: { code: "BKK", city: "Bangkok", country: "Tayland", group: "Güney ve Güneydoğu Asya", minNights: 8, maxNights: 12, weekendOnly: false, visaSafe: true, weatherNote: "Çok yüksek nem ve muson elenir", tripPlan: "8–12 gün Bangkok–sahil" },
  HKT: { code: "HKT", city: "Phuket", country: "Tayland", group: "Güney ve Güneydoğu Asya", minNights: 8, maxNights: 12, weekendOnly: false, visaSafe: true, weatherNote: "Deniz, nem ve muson birlikte kontrol edilir", tripPlan: "8–12 gün deniz ve gece hayatı" },
  CMB: { code: "CMB", city: "Kolombo", country: "Sri Lanka", group: "Güney ve Güneydoğu Asya", minNights: 8, maxNights: 12, weekendOnly: false, visaSafe: false, weatherNote: "İki muson dönemi ayrı kontrol edilir", tripPlan: "8–12 gün Kolombo–Kandy–Galle" },
  SIN: { code: "SIN", city: "Singapur", country: "Singapur", group: "Güney ve Güneydoğu Asya", minNights: 3, maxNights: 5, weekendOnly: false, visaSafe: true, weatherNote: "Yüksek nem uyarıyla gösterilir", tripPlan: "3–5 gün şehir veya aktarma" },
  ZNZ: { code: "ZNZ", city: "Zanzibar", country: "Tanzanya", group: "Müslüman Asya", minNights: 7, maxNights: 10, weekendOnly: false, visaSafe: false, weatherNote: "Deniz, nem ve yağmur sezonu kontrol edilir", tripPlan: "7–10 gün ada" },
  MRU: { code: "MRU", city: "Mauritius", country: "Mauritius", group: "Güney ve Güneydoğu Asya", minNights: 7, maxNights: 10, weekendOnly: false, visaSafe: true, weatherNote: "Deniz ve siklon dönemi kontrol edilir", tripPlan: "7–10 gün ada" },
  TYO: { code: "TYO", arrivalId: "HND,NRT", city: "Tokyo", country: "Japonya", group: "Uzak rotalar", minNights: 8, maxNights: 14, weekendOnly: false, visaSafe: true, weatherNote: "Aşırı sıcak, tayfun ve sert soğuk elenir", tripPlan: "8–14 gün Tokyo–Kyoto–Osaka" },
  KIX: { code: "KIX", city: "Osaka", country: "Japonya", group: "Uzak rotalar", minNights: 8, maxNights: 14, weekendOnly: false, visaSafe: true, weatherNote: "Aşırı sıcak, tayfun ve sert soğuk elenir", tripPlan: "8–14 gün Osaka–Kyoto–Tokyo" },
  ICN: { code: "ICN", city: "Seul", country: "Güney Kore", group: "Uzak rotalar", minNights: 7, maxNights: 10, weekendOnly: false, visaSafe: false, weatherNote: "Sert soğuk ve yüksek nem elenir", tripPlan: "7–10 gün Seul–Busan" },
  KSY: { code: "KSY", city: "Kars", country: "Türkiye", group: "Türkiye", minNights: 2, maxNights: 4, weekendOnly: false, visaSafe: true, weatherNote: "0°C altı günler elenir", tripPlan: "2–4 gün Kars–Ani" },
  VAN: { code: "VAN", city: "Van", country: "Türkiye", group: "Türkiye", minNights: 3, maxNights: 5, weekendOnly: false, visaSafe: true, weatherNote: "0°C altı günler elenir", tripPlan: "3–5 gün Van–Tatvan" },
  ERZ: { code: "ERZ", city: "Erzurum", country: "Türkiye", group: "Türkiye", minNights: 2, maxNights: 4, weekendOnly: false, visaSafe: true, weatherNote: "0°C altı günler elenir", tripPlan: "2–4 gün şehir ve doğa" },
  IGD: { code: "IGD", city: "Iğdır", country: "Türkiye", group: "Türkiye", minNights: 3, maxNights: 5, weekendOnly: false, visaSafe: true, weatherNote: "0°C altı günler elenir", tripPlan: "3–5 gün Doğubayazıt rotası" },
  ERC: { code: "ERC", city: "Erzincan", country: "Türkiye", group: "Türkiye", minNights: 2, maxNights: 4, weekendOnly: false, visaSafe: true, weatherNote: "0°C altı günler elenir", tripPlan: "2–4 gün şehir ve doğa" },
  EZS: { code: "EZS", city: "Elazığ", country: "Türkiye", group: "Türkiye", minNights: 3, maxNights: 5, weekendOnly: false, visaSafe: true, weatherNote: "0°C altı günler elenir", tripPlan: "3–5 gün Elazığ–Tunceli" },
  MOW: {"code": "MOW", "city": "Moskova", "country": "Rusya", "group": "Rusya", "minNights": 4, "maxNights": 7, "weekendOnly": false, "visaSafe": false, "weatherNote": "Sert soğuk ve deniz sezonu ayrıca kontrol edilir", "tripPlan": "4–7 gece Moskova; St. Petersburg ile uzatılabilir", "checkedAt": "2026-10-08", "entrySourceUrl": "https://evisa.kdmid.ru/", "entryNote": "Bordo pasaport için e-vize gerekir; uygun giriş kapısı ve sigorta şartı kontrol edilir.", "riskNote": "Seyahat uyarıları, uçuş değişiklikleri ve ödeme imkânları ayrıca kontrol edilmeli. Yalnız seçerek taranır.", "manualOnly": true, "arrivalId": "SVO,DME,VKO"},
  LED: {"code": "LED", "city": "St. Petersburg", "country": "Rusya", "group": "Rusya", "minNights": 4, "maxNights": 7, "weekendOnly": false, "visaSafe": false, "weatherNote": "Sert soğuk ve deniz sezonu ayrıca kontrol edilir", "tripPlan": "4–7 gece sanat, mimari ve şehir", "checkedAt": "2026-10-08", "entrySourceUrl": "https://evisa.kdmid.ru/", "entryNote": "Bordo pasaport için e-vize gerekir; uygun giriş kapısı ve sigorta şartı kontrol edilir.", "riskNote": "Seyahat uyarıları, uçuş değişiklikleri ve ödeme imkânları ayrıca kontrol edilmeli. Yalnız seçerek taranır.", "manualOnly": true},
  KZN: {"code": "KZN", "city": "Kazan", "country": "Rusya", "group": "Rusya", "minNights": 3, "maxNights": 5, "weekendOnly": false, "visaSafe": false, "weatherNote": "Sert soğuk ve deniz sezonu ayrıca kontrol edilir", "tripPlan": "3–5 gece Tatar kültürü ve yemek", "checkedAt": "2026-10-08", "entrySourceUrl": "https://evisa.kdmid.ru/", "entryNote": "Bordo pasaport için e-vize gerekir; uygun giriş kapısı ve sigorta şartı kontrol edilir.", "riskNote": "Seyahat uyarıları, uçuş değişiklikleri ve ödeme imkânları ayrıca kontrol edilmeli. Yalnız seçerek taranır.", "manualOnly": true},
  AER: {"code": "AER", "city": "Soçi", "country": "Rusya", "group": "Rusya", "minNights": 4, "maxNights": 7, "weekendOnly": false, "visaSafe": false, "weatherNote": "Sert soğuk ve deniz sezonu ayrıca kontrol edilir", "tripPlan": "4–7 gece sahil ve doğa; deniz sezonu ayrıca kontrol edilir", "checkedAt": "2026-10-08", "entrySourceUrl": "https://evisa.kdmid.ru/", "entryNote": "Bordo pasaport için e-vize gerekir; uygun giriş kapısı ve sigorta şartı kontrol edilir.", "riskNote": "Seyahat uyarıları, uçuş değişiklikleri ve ödeme imkânları ayrıca kontrol edilmeli. Yalnız seçerek taranır.", "manualOnly": true},
  BUS: {"code": "BUS", "city": "Batum", "country": "Gürcistan", "group": "Kafkasya", "minNights": 2, "maxNights": 4, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "2–4 gece sahil, şehir ve gece hayatı", "checkedAt": "2026-10-08", "entrySourceUrl": "https://www.mfa.gov.tr/turk-vatandaslarinin-tabi-oldugu-vize-uygulamalari.tr.mfa", "entryNote": "Yeni tip kimlik veya pasaportla giriş; 2026 seyahat sağlık/kaza sigortası şartını kontrol et."},
  KUT: {"code": "KUT", "city": "Kutaisi", "country": "Gürcistan", "group": "Kafkasya", "minNights": 3, "maxNights": 5, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "3–5 gece Kutaisi, kanyon ve mağaralar", "checkedAt": "2026-10-08", "entrySourceUrl": "https://www.mfa.gov.tr/turk-vatandaslarinin-tabi-oldugu-vize-uygulamalari.tr.mfa", "entryNote": "Yeni tip kimlik veya pasaportla giriş; 2026 seyahat sağlık/kaza sigortası şartını kontrol et."},
  TIV: {"code": "TIV", "city": "Tivat", "country": "Karadağ", "group": "Balkanlar", "minNights": 3, "maxNights": 5, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "3–5 gece Kotor, Perast ve Budva", "checkedAt": "2026-10-08", "entrySourceUrl": "https://www.mfa.gov.tr/turk-vatandaslarinin-tabi-oldugu-vize-uygulamalari.tr.mfa", "entryNote": "Kısa turistik seyahatte vize muafiyeti; pasaport ve giriş koşulları resmî kaynaktan kontrol edilmeli."},
  TNG: {"code": "TNG", "city": "Tanca", "country": "Fas", "group": "Fas ve Kuzey Afrika", "minNights": 5, "maxNights": 8, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "5–8 gece Tanca–Şafşavan; Fas içi ulaşım ayrıca aranır", "checkedAt": "2026-10-08", "entrySourceUrl": "https://www.mfa.gov.tr/turk-vatandaslarinin-tabi-oldugu-vize-uygulamalari.tr.mfa", "entryNote": "Kısa turistik seyahatte vize muafiyeti; pasaport ve giriş koşulları resmî kaynaktan kontrol edilmeli."},
  MLE: {"code": "MLE", "city": "Malé / Maldivler", "country": "Maldivler", "group": "Müslüman Asya", "minNights": 7, "maxNights": 10, "weekendOnly": false, "visaSafe": false, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "7–10 gece yerel ada; ada transferi ayrıca fiyatlanır", "checkedAt": "2026-10-08", "entrySourceUrl": "https://www.mfa.gov.tr/turk-vatandaslarinin-tabi-oldugu-vize-uygulamalari.tr.mfa", "entryNote": "Kapıda vize koşulları, konaklama ve ada transferi kontrol edilmeli."},
  PEN: {"code": "PEN", "city": "Penang", "country": "Malezya", "group": "Müslüman Asya", "minNights": 7, "maxNights": 10, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "7–10 gece George Town, yemek ve Langkawi", "checkedAt": "2026-10-08", "entrySourceUrl": "https://www.mfa.gov.tr/turk-vatandaslarinin-tabi-oldugu-vize-uygulamalari.tr.mfa", "entryNote": "Bordo pasaport için girişte ücretsiz turistik vize; varış kartı ve giriş koşullarını kontrol et."},
  BWN: {"code": "BWN", "city": "Bandar Seri Begavan", "country": "Brunei", "group": "Müslüman Asya", "minNights": 4, "maxNights": 7, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "4–7 gece Brunei ve doğa", "checkedAt": "2026-10-08", "entrySourceUrl": "https://www.mfa.gov.tr/turk-vatandaslarinin-tabi-oldugu-vize-uygulamalari.tr.mfa", "entryNote": "Kısa turistik seyahatte vize muafiyeti; pasaport ve giriş koşulları resmî kaynaktan kontrol edilmeli."},
  HAN: {"code": "HAN", "city": "Hanoi", "country": "Vietnam", "group": "Güney ve Güneydoğu Asya", "minNights": 8, "maxNights": 12, "weekendOnly": false, "visaSafe": false, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "8–12 gece Hanoi–Ninh Binh–Ha Long", "checkedAt": "2026-10-08", "entrySourceUrl": "https://www.mfa.gov.tr/turk-vatandaslarinin-tabi-oldugu-vize-uygulamalari.tr.mfa", "entryNote": "Bordo pasaport için seyahatten önce e-vize gerekir."},
  DAD: {"code": "DAD", "city": "Da Nang", "country": "Vietnam", "group": "Güney ve Güneydoğu Asya", "minNights": 8, "maxNights": 12, "weekendOnly": false, "visaSafe": false, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "8–12 gece Da Nang–Hoi An; deniz sezonu kontrol edilir", "checkedAt": "2026-10-08", "entrySourceUrl": "https://www.mfa.gov.tr/turk-vatandaslarinin-tabi-oldugu-vize-uygulamalari.tr.mfa", "entryNote": "Bordo pasaport için seyahatten önce e-vize gerekir."},
  MNL: {"code": "MNL", "city": "Manila", "country": "Filipinler", "group": "Güney ve Güneydoğu Asya", "minNights": 8, "maxNights": 12, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "8–12 gece Manila ve ada bağlantıları", "checkedAt": "2026-10-08", "entrySourceUrl": "https://www.mfa.gov.tr/turk-vatandaslarinin-tabi-oldugu-vize-uygulamalari.tr.mfa", "entryNote": "Kısa turistik seyahatte vize muafiyeti; pasaport ve giriş koşulları resmî kaynaktan kontrol edilmeli."},
  CEB: {"code": "CEB", "city": "Cebu", "country": "Filipinler", "group": "Güney ve Güneydoğu Asya", "minNights": 8, "maxNights": 12, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "8–12 gece Cebu–Bohol; ada ulaşımı ayrıca aranır", "checkedAt": "2026-10-08", "entrySourceUrl": "https://www.mfa.gov.tr/turk-vatandaslarinin-tabi-oldugu-vize-uygulamalari.tr.mfa", "entryNote": "Kısa turistik seyahatte vize muafiyeti; pasaport ve giriş koşulları resmî kaynaktan kontrol edilmeli."},
  KTM: {"code": "KTM", "city": "Katmandu", "country": "Nepal", "group": "Güney ve Güneydoğu Asya", "minNights": 7, "maxNights": 10, "weekendOnly": false, "visaSafe": false, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "7–10 gece Katmandu–Pokhara; yürüyüş izinleri ayrıca kontrol edilir", "checkedAt": "2026-10-08", "entrySourceUrl": "https://www.mfa.gov.tr/turk-vatandaslarinin-tabi-oldugu-vize-uygulamalari.tr.mfa", "entryNote": "Kapıda vize koşulları ve gerekiyorsa yürüyüş izinleri kontrol edilmeli."},
  ADB: {"code": "ADB", "city": "İzmir", "country": "Türkiye", "group": "Türkiye", "minNights": 2, "maxNights": 4, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "2–4 gece İzmir–Urla veya Selçuk", "checkedAt": "2026-10-08"},
  AYT: {"code": "AYT", "city": "Antalya", "country": "Türkiye", "group": "Türkiye", "minNights": 3, "maxNights": 5, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "3–5 gece şehir, sahil ve antik kentler", "checkedAt": "2026-10-08"},
  DLM: {"code": "DLM", "city": "Dalaman / Fethiye", "country": "Türkiye", "group": "Türkiye", "minNights": 3, "maxNights": 5, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "3–5 gece Fethiye–Ölüdeniz; havalimanı transferi eklenir", "checkedAt": "2026-10-08"},
  BJV: {"code": "BJV", "city": "Bodrum", "country": "Türkiye", "group": "Türkiye", "minNights": 3, "maxNights": 5, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "3–5 gece Bodrum ve sahil", "checkedAt": "2026-10-08"},
  ASR: {"code": "ASR", "city": "Kayseri / Kapadokya", "country": "Türkiye", "group": "Türkiye", "minNights": 2, "maxNights": 4, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "2–4 gece Kayseri veya Kapadokya; bölge transferi ayrıca aranır", "checkedAt": "2026-10-08"},
  NAV: {"code": "NAV", "city": "Nevşehir / Kapadokya", "country": "Türkiye", "group": "Türkiye", "minNights": 2, "maxNights": 4, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "2–4 gece Göreme–Avanos–Ürgüp", "checkedAt": "2026-10-08"},
  TZX: {"code": "TZX", "city": "Trabzon", "country": "Türkiye", "group": "Türkiye", "minNights": 3, "maxNights": 5, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "3–5 gece Trabzon–Uzungöl; araç/tur maliyeti ayrıca hesaplanır", "checkedAt": "2026-10-08"},
  SZF: {"code": "SZF", "city": "Samsun", "country": "Türkiye", "group": "Türkiye", "minNights": 2, "maxNights": 4, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "2–4 gece Samsun ve kıyı", "checkedAt": "2026-10-08"},
  SIC: {"code": "SIC", "city": "Sinop", "country": "Türkiye", "group": "Türkiye", "minNights": 2, "maxNights": 4, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "2–4 gece şehir, sahil ve Hamsilos", "checkedAt": "2026-10-08"},
  MZH: {"code": "MZH", "city": "Amasya / Merzifon", "country": "Türkiye", "group": "Türkiye", "minNights": 2, "maxNights": 4, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "2–4 gece Amasya; Merzifon transferi ayrıca aranır", "checkedAt": "2026-10-08"},
  MLX: {"code": "MLX", "city": "Malatya", "country": "Türkiye", "group": "Türkiye", "minNights": 2, "maxNights": 4, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "2–4 gece Malatya ve Arslantepe", "checkedAt": "2026-10-08"},
  MSR: {"code": "MSR", "city": "Muş / Bitlis–Tatvan", "country": "Türkiye", "group": "Türkiye", "minNights": 3, "maxNights": 5, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "3–5 gece Muş veya Bitlis–Tatvan; kara bağlantısı ayrıca aranır", "checkedAt": "2026-10-08"},
  EDIRNE: {"code": "EDIRNE", "city": "Edirne", "country": "Türkiye", "group": "Türkiye", "minNights": 2, "maxNights": 3, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "2–3 gece Selimiye, Meriç ve yerel yemek", "transportMode": "ground", "transportLinks": [{"label": "Ankara–Edirne otobüslerini ara", "url": "https://www.obilet.com/otobus-bileti/ankara-edirne"}, {"label": "TCDD bilet ve bağlantılarını kontrol et", "url": "https://bilet.tcdd.gov.tr/"}], "entryNote": "Ankara → Edirne otobüsü; alternatif İstanbul üzerinden kara bağlantısı.", "checkedAt": "2026-10-08"},
  ESKISEHIR: {"code": "ESKISEHIR", "city": "Eskişehir", "country": "Türkiye", "group": "Türkiye", "minNights": 1, "maxNights": 2, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "1–2 gece Odunpazarı ve Porsuk", "transportMode": "ground", "transportLinks": [{"label": "Ankara–Eskişehir otobüslerini ara", "url": "https://www.obilet.com/otobus-bileti/ankara-eskisehir"}, {"label": "TCDD bilet ve bağlantılarını kontrol et", "url": "https://bilet.tcdd.gov.tr/"}], "entryNote": "Ankara → Eskişehir YHT veya otobüs.", "checkedAt": "2026-10-08"},
  SAFRANBOLU: {"code": "SAFRANBOLU", "city": "Safranbolu", "country": "Türkiye", "group": "Türkiye", "minNights": 1, "maxNights": 2, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "1–2 gece tarihî çarşı ve konaklar", "transportMode": "ground", "transportLinks": [{"label": "Ankara–Safranbolu otobüslerini ara", "url": "https://www.obilet.com/otobus-bileti/ankara-safranbolu"}], "entryNote": "Ankara → Safranbolu otobüsü.", "checkedAt": "2026-10-08"},
  AMASRA: {"code": "AMASRA", "city": "Amasra", "country": "Türkiye", "group": "Türkiye", "minNights": 2, "maxNights": 3, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "2–3 gece sahil, manzara ve yemek", "transportMode": "ground", "transportLinks": [{"label": "Ankara–Amasra otobüslerini ara", "url": "https://www.obilet.com/otobus-bileti/ankara-amasra"}], "entryNote": "Ankara → Amasra otobüsü; Bartın üzerinden bağlantı ayrıca kontrol edilir.", "checkedAt": "2026-10-08"},
  BOLU: {"code": "BOLU", "city": "Bolu", "country": "Türkiye", "group": "Türkiye", "minNights": 1, "maxNights": 2, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "1–2 gece Abant veya Gölcük; şehir dışı ulaşım eklenir", "transportMode": "ground", "transportLinks": [{"label": "Ankara–Bolu otobüslerini ara", "url": "https://www.obilet.com/otobus-bileti/ankara-bolu"}], "entryNote": "Ankara → Bolu otobüsü; göl/park transferleri ayrıca aranır.", "checkedAt": "2026-10-08"},
  BURSA: {"code": "BURSA", "city": "Bursa", "country": "Türkiye", "group": "Türkiye", "minNights": 2, "maxNights": 3, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "2–3 gece tarihî merkez ve yemek", "transportMode": "ground", "transportLinks": [{"label": "Ankara–Bursa otobüslerini ara", "url": "https://www.obilet.com/otobus-bileti/ankara-bursa"}], "entryNote": "Ankara → Bursa otobüsü; Uludağ seçilirse bölge ulaşımı eklenir.", "checkedAt": "2026-10-08"},
  CANAKKALE: {"code": "CANAKKALE", "city": "Çanakkale", "country": "Türkiye", "group": "Türkiye", "minNights": 2, "maxNights": 4, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "2–4 gece merkez–Troya; Bozcaada için feribot eklenir", "transportMode": "ground", "transportLinks": [{"label": "Ankara–Çanakkale otobüslerini ara", "url": "https://www.obilet.com/otobus-bileti/ankara-canakkale"}], "entryNote": "Ankara → Çanakkale otobüsü; ada ulaşımı ayrıca kontrol edilir.", "checkedAt": "2026-10-08"},
  KONYA: {"code": "KONYA", "city": "Konya", "country": "Türkiye", "group": "Türkiye", "minNights": 1, "maxNights": 2, "weekendOnly": false, "visaSafe": true, "weatherNote": "Mevsim ve hava koşulları seyahat öncesinde kontrol edilir", "tripPlan": "1–2 gece Mevlana, tarih ve yemek", "transportMode": "ground", "transportLinks": [{"label": "Ankara–Konya otobüslerini ara", "url": "https://www.obilet.com/otobus-bileti/ankara-konya"}, {"label": "TCDD bilet ve bağlantılarını kontrol et", "url": "https://bilet.tcdd.gov.tr/"}], "entryNote": "Ankara → Konya YHT veya otobüs.", "checkedAt": "2026-10-08"},
};

export const CORE_DESTINATION_CODES = ["TBS", "GYD", "VAS", "CMN", "TAS", "TYO", "KIX"];
export const GROUP_ORDER = ["Türkiye", "Balkanlar", "Kafkasya", "Fas ve Kuzey Afrika", "Türk dünyası", "Rusya", "Müslüman Asya", "Güney ve Güneydoğu Asya", "Uzak rotalar"];

export function isFlightDestination(destination: Destination | undefined): destination is Destination {
  return Boolean(destination && destination.transportMode !== "ground");
}

export function todayDestinationCodes(date = new Date()) {
  const rotating = Object.keys(DESTINATIONS).filter((code) => !CORE_DESTINATION_CODES.includes(code) && isFlightDestination(DESTINATIONS[code]) && !DESTINATIONS[code].manualOnly);
  const day = Math.floor(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()) / 86_400_000);
  const start = (day * 5) % rotating.length;
  const extras = Array.from({ length: Math.min(5, rotating.length) }, (_, index) => rotating[(start + index) % rotating.length]);
  return [...CORE_DESTINATION_CODES, ...extras];
}

